-- Migration V4: Add RFID Cards and Privacy Settings Tables

CREATE TABLE IF NOT EXISTS rfid_cards (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    card_number VARCHAR(100) UNIQUE NOT NULL,
    card_uid VARCHAR(100) UNIQUE NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    linked_vehicle VARCHAR(255),
    issued_date DATE,
    last_used TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS privacy_settings (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    location_permission BOOLEAN NOT NULL DEFAULT TRUE,
    location_sharing BOOLEAN NOT NULL DEFAULT TRUE,
    nearby_charger_personalization BOOLEAN NOT NULL DEFAULT TRUE,
    push_notifications BOOLEAN NOT NULL DEFAULT TRUE,
    charging_activity_visibility BOOLEAN NOT NULL DEFAULT TRUE,
    usage_analytics BOOLEAN NOT NULL DEFAULT TRUE,
    personalized_recommendations BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
